//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sincronizados.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sincronizados.WEB.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application date.
        /// </summary>
        public static string ApplicationDate {
            get {
                return ResourceManager.GetString("ApplicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application.
        /// </summary>
        public static string ApplicationNumber {
            get {
                return ResourceManager.GetString("ApplicationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approval date.
        /// </summary>
        public static string ApprovalDate {
            get {
                return ResourceManager.GetString("ApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacation approval.
        /// </summary>
        public static string ApprovalVacation {
            get {
                return ResourceManager.GetString("ApprovalVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approve request.
        /// </summary>
        public static string ApproveRequest {
            get {
                return ResourceManager.GetString("ApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approve transfer.
        /// </summary>
        public static string ApproveTransfer {
            get {
                return ResourceManager.GetString("ApproveTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approve purchase order.
        /// </summary>
        public static string AproveOC {
            get {
                return ResourceManager.GetString("AproveOC", resourceCulture);
            }
        }

        public static string AreYouSure
        {
            get
            {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Network integration with AX not available.
        /// </summary>
        public static string AXConectionError {
            get {
                return ResourceManager.GetString("AXConectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balances.
        /// </summary>
        public static string Balances {
            get {
                return ResourceManager.GetString("Balances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a reason for the request.
        /// </summary>
        public static string CardChReason {
            get {
                return ResourceManager.GetString("CardChReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change company.
        /// </summary>
        public static string ChanceCompany {
            get {
                return ResourceManager.GetString("ChanceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change made successfully.
        /// </summary>
        public static string ChanceCompanyCorrect {
            get {
                return ResourceManager.GetString("ChanceCompanyCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colones.
        /// </summary>
        public static string Colones {
            get {
                return ResourceManager.GetString("Colones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select the company!.
        /// </summary>
        public static string CompanyError {
            get {
                return ResourceManager.GetString("CompanyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check the internet connection.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidated balance.
        /// </summary>
        public static string ConsolidatedBalance {
            get {
                return ResourceManager.GetString("ConsolidatedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit limit.
        /// </summary>
        public static string Creditlimit {
            get {
                return ResourceManager.GetString("Creditlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer account.
        /// </summary>
        public static string CustomerAccount {
            get {
                return ResourceManager.GetString("CustomerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Details.
        /// </summary>
        public static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer invoices.
        /// </summary>
        public static string CustomerInvoices {
            get {
                return ResourceManager.GetString("CustomerInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer list.
        /// </summary>
        public static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accumulated days.
        /// </summary>
        public static string DaysAccumulated {
            get {
                return ResourceManager.GetString("DaysAccumulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days Enjoyed.
        /// </summary>
        public static string DaysEnjoyed {
            get {
                return ResourceManager.GetString("DaysEnjoyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending days.
        /// </summary>
        public static string DaysPending {
            get {
                return ResourceManager.GetString("DaysPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direct collaborators.
        /// </summary>
        public static string DirectCollaborators {
            get {
                return ResourceManager.GetString("DirectCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employment certificate.
        /// </summary>
        public static string Doc1 {
            get {
                return ResourceManager.GetString("Doc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salarial constance.
        /// </summary>
        public static string Doc2 {
            get {
                return ResourceManager.GetString("Doc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proof of income.
        /// </summary>
        public static string Doc3 {
            get {
                return ResourceManager.GetString("Doc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proof of payment.
        /// </summary>
        public static string Doc4 {
            get {
                return ResourceManager.GetString("Doc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The document request has already been sent for approval, you must wait for the AX response..
        /// </summary>
        public static string DocSendValid {
            get {
                return ResourceManager.GetString("DocSendValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document date.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dollars.
        /// </summary>
        public static string Dollars {
            get {
                return ResourceManager.GetString("Dollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Due date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The employee does not exist!.
        /// </summary>
        public static string EmployeeError {
            get {
                return ResourceManager.GetString("EmployeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee services.
        /// </summary>
        public static string EmployeeServices {
            get {
                return ResourceManager.GetString("EmployeeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration.
        /// </summary>
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        public static string FDate {
            get {
                return ResourceManager.GetString("FDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From the camera.
        /// </summary>
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From the gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Holidays.
        /// </summary>
        public static string HolidayInformation {
            get {
                return ResourceManager.GetString("HolidayInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identification card.
        /// </summary>
        public static string IdentificationCard {
            get {
                return ResourceManager.GetString("IdentificationCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Identification card.
        /// </summary>
        public static string IdentificationCardValid
        {
            get
            {
                return ResourceManager.GetString("IdentificationCardValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string InfoMessage {
            get {
                return ResourceManager.GetString("InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interest.
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal transfers.
        /// </summary>
        public static string InternalTransfer {
            get {
                return ResourceManager.GetString("InternalTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice balance.
        /// </summary>
        public static string InvoiceBalance {
            get {
                return ResourceManager.GetString("InvoiceBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice date.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leases.
        /// </summary>
        public static string Leases {
            get {
                return ResourceManager.GetString("Leases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legal ID.
        /// </summary>
        public static string LegalID {
            get {
                return ResourceManager.GetString("LegalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or password wrong!.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My data.
        /// </summary>
        public static string MyData {
            get {
                return ResourceManager.GetString("MyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a new version of the application, please update..
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device does not support access to the camera.
        /// </summary>
        public static string NoCameraSupported {
            get {
                return ResourceManager.GetString("NoCameraSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a document.
        /// </summary>
        public static string NoDocSelect {
            get {
                return ResourceManager.GetString("NoDocSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device does not support access to the gallery.
        /// </summary>
        public static string NoGallerySupported {
            get {
                return ResourceManager.GetString("NoGallerySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No image to send.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user does not have a valid login in Dynamics AX.
        /// </summary>
        public static string NoUserAX {
            get {
                return ResourceManager.GetString("NoUserAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opening.
        /// </summary>
        public static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origin of photography?.
        /// </summary>
        public static string OriginPhotography {
            get {
                return ResourceManager.GetString("OriginPhotography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter the password!.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment conditions.
        /// </summary>
        public static string PayConditions {
            get {
                return ResourceManager.GetString("PayConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to process the selected transfers?.
        /// </summary>
        public static string ProcessTransfer {
            get {
                return ResourceManager.GetString("ProcessTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider account.
        /// </summary>
        public static string ProviderAccount {
            get {
                return ResourceManager.GetString("ProviderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Providers name.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchases to be approved.
        /// </summary>
        public static string PurchAprov {
            get {
                return ResourceManager.GetString("PurchAprov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase order detail.
        /// </summary>
        public static string PurchaseOrderDetail {
            get {
                return ResourceManager.GetString("PurchaseOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purch date.
        /// </summary>
        public static string PurchDate {
            get {
                return ResourceManager.GetString("PurchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase order.
        /// </summary>
        public static string PurchOrder {
            get {
                return ResourceManager.GetString("PurchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The purchase order has already been sent, you must wait for the answer from AX..
        /// </summary>
        public static string PurchSendValid {
            get {
                return ResourceManager.GetString("PurchSendValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purch total.
        /// </summary>
        public static string PurchTotal {
            get {
                return ResourceManager.GetString("PurchTotal", resourceCulture);
            }
        }

        public static string PushRegistrationSuccess
        {
            get
            {
                return ResourceManager.GetString("PushRegistrationSuccess", resourceCulture);
            }
        }

        public static string PushDesregistrationSuccess
        {
            get
            {
                return ResourceManager.GetString("PushDesregistrationSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reason for rejection.
        /// </summary>
        public static string ReasonRejection {
            get {
                return ResourceManager.GetString("ReasonRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request has been registered!.
        /// </summary>
        public static string RegisterRequest {
            get {
                return ResourceManager.GetString("RegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject purchase order.
        /// </summary>
        public static string RejectOC {
            get {
                return ResourceManager.GetString("RejectOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject request.
        /// </summary>
        public static string RejectRequest {
            get {
                return ResourceManager.GetString("RejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a reason for rejection.
        /// </summary>
        public static string RejectValidation {
            get {
                return ResourceManager.GetString("RejectValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renew card.
        /// </summary>
        public static string RenewCard {
            get {
                return ResourceManager.GetString("RenewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replacement for loss.
        /// </summary>
        public static string Rep1 {
            get {
                return ResourceManager.GetString("Rep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replacement for impairment.
        /// </summary>
        public static string Rep2 {
            get {
                return ResourceManager.GetString("Rep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change of company or position.
        /// </summary>
        public static string Rep3 {
            get {
                return ResourceManager.GetString("Rep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request.
        /// </summary>
        public static string RequestAti {
            get {
                return ResourceManager.GetString("RequestAti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request card.
        /// </summary>
        public static string RequestCard {
            get {
                return ResourceManager.GetString("RequestCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request document.
        /// </summary>
        public static string RequestDocument {
            get {
                return ResourceManager.GetString("RequestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document request.
        /// </summary>
        public static string RequestDocuments {
            get {
                return ResourceManager.GetString("RequestDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requested document.
        /// </summary>
        public static string RequestedDocument {
            get {
                return ResourceManager.GetString("RequestedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request history.
        /// </summary>
        public static string RequestHistory {
            get {
                return ResourceManager.GetString("RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renovation request.
        /// </summary>
        public static string RequestRewCard {
            get {
                return ResourceManager.GetString("RequestRewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests and inquiries.
        /// </summary>
        public static string RequestsInquiries {
            get {
                return ResourceManager.GetString("RequestsInquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests made.
        /// </summary>
        public static string RequestsMade {
            get {
                return ResourceManager.GetString("RequestsMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return transfer.
        /// </summary>
        public static string ReturnTransfer {
            get {
                return ResourceManager.GetString("ReturnTransfer", resourceCulture);
            }
        }

        public static string ReportPrint
        {
            get
            {
                return ResourceManager.GetString("ReportPrint", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string SDate {
            get {
                return ResourceManager.GetString("SDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search customer.
        /// </summary>
        public static string SearchCustomer {
            get {
                return ResourceManager.GetString("SearchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search invoice.
        /// </summary>
        public static string SearchInvoice {
            get {
                return ResourceManager.GetString("SearchInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search internal transfer.
        /// </summary>
        public static string SearchTransfer {
            get {
                return ResourceManager.GetString("SearchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the document:.
        /// </summary>
        public static string SelectDocument {
            get {
                return ResourceManager.GetString("SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request has been sent!.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.Type.
        /// </summary>
        public static string SType {
            get {
                return ResourceManager.GetString("SType", resourceCulture);
            }
        }

        public static string Success
        {
            get
            {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Term.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer details.
        /// </summary>
        public static string TransferDetails {
            get {
                return ResourceManager.GetString("TransferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfers selected.
        /// </summary>
        public static string TransferError {
            get {
                return ResourceManager.GetString("TransferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected transfers have already been processed.
        /// </summary>
        public static string TransferError1 {
            get {
                return ResourceManager.GetString("TransferError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The transfer has already been sent for approval, you must wait for the response from the AX..
        /// </summary>
        public static string TransferSendValid {
            get {
                return ResourceManager.GetString("TransferSendValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaction id.
        /// </summary>
        public static string TransId {
            get {
                return ResourceManager.GetString("TransId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter the user!.
        /// </summary>
        public static string UserNameError {
            get {
                return ResourceManager.GetString("UserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacation.
        /// </summary>
        public static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacation history.
        /// </summary>
        public static string VacationHistory {
            get {
                return ResourceManager.GetString("VacationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacation inventory.
        /// </summary>
        public static string VacationInventory {
            get {
                return ResourceManager.GetString("VacationInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacation request.
        /// </summary>
        public static string VacationRequest {
            get {
                return ResourceManager.GetString("VacationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application dates must be valid.
        /// </summary>
        public static string ValidDates {
            get {
                return ResourceManager.GetString("ValidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of days greater than the available balance.
        /// </summary>
        public static string ValidQtyDays {
            get {
                return ResourceManager.GetString("ValidQtyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select the type.
        /// </summary>
        public static string ValidtypeVac {
            get {
                return ResourceManager.GetString("ValidtypeVac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V.residual.
        /// </summary>
        public static string Vresidual {
            get {
                return ResourceManager.GetString("Vresidual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Welcolme!.
        /// </summary>
        public static string Welcolme {
            get {
                return ResourceManager.GetString("Welcolme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave with salary.
        /// </summary>
        public static string WithPay {
            get {
                return ResourceManager.GetString("WithPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
